"""Reference lists for settings (moved from the retired settings_routes.py in UI Migration Phase 5)."""

COMMON_COUNTRIES = [
    ("US", "United States"),
    ("CA", "Canada"),
    ("GB", "United Kingdom"),
    ("AU", "Australia"),
    ("DE", "Germany"),
    ("FR", "France"),
    ("JP", "Japan"),
    ("BR", "Brazil"),
    ("IN", "India"),
    ("MX", "Mexico"),
    ("NZ", "New Zealand"),
    ("ZA", "South Africa"),
    ("IT", "Italy"),
    ("ES", "Spain"),
    ("NL", "Netherlands"),
    ("SE", "Sweden"),
    ("CH", "Switzerland"),
    ("IE", "Ireland"),
    ("SG", "Singapore"),
    ("HK", "Hong Kong"),
    ("KR", "South Korea"),
    ("CN", "China"),
    ("AE", "United Arab Emirates"),
    ("AR", "Argentina"),
]

COMMON_TIMEZONES = [
    "UTC",
    "US/Eastern", "US/Central", "US/Mountain", "US/Pacific",
    "US/Alaska", "US/Hawaii",
    "Canada/Atlantic", "Canada/Eastern", "Canada/Central",
    "Canada/Mountain", "Canada/Pacific",
    "Europe/London", "Europe/Paris", "Europe/Berlin", "Europe/Rome",
    "Europe/Madrid", "Europe/Amsterdam", "Europe/Stockholm", "Europe/Moscow",
    "Asia/Tokyo", "Asia/Shanghai", "Asia/Hong_Kong", "Asia/Singapore",
    "Asia/Kolkata", "Asia/Dubai", "Asia/Seoul",
    "Australia/Sydney", "Australia/Melbourne", "Australia/Perth",
    "Pacific/Auckland",
    "America/Sao_Paulo", "America/Mexico_City", "America/Argentina/Buenos_Aires",
    "Africa/Johannesburg", "Africa/Cairo",
]
